version: "3.7"

services:
  apache:
    build: apache
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./apache/demo:/var/www/html/demo
    links:
      - shiny_app
      - unshiny_app
      
  shiny_app:
    image: shinytglqc_shiny:latest
    restart: always
    # Setting this to something other than 'root' will cause shiny apps not to
    # run on the localhost:80 "Welcome to Shiny" diagnostics page mentioned
    # below.
    user: 'root'
    # comment out lines below to enable application logs STDOUT output
    environment:
      - APPLICATION_LOGS_TO_STDOUT=false
    expose:
      - '3838'
    volumes:
      - './shiny_logs:/var/log/shiny-server'
      # Mount wherever the data is onto the shiny container
      - './data:/srv/shiny-server/data'



  # a simple webapp based on the docker-compose tutorial
  # https://docs.docker.com/compose/gettingstarted/
  unshiny_app:
    build: unshiny
    expose:
      - "5000"

  redis:
    image: "redis:alpine"
      
