#! /usr/bin/env bash
set -eo pipefail

perl -p -i -e 's/TGL01/PROJECT_QUINOA/g' data/*.txt
perl -p -i -e 's/INSPIRE/QUINOA/g' data/*.txt
perl -p -i -e 's/TGL03/PROJECT_ALPHA/g' data/*.txt
perl -p -i -e 's/BHPV/ALPHA/g' data/*.txt
perl -p -i -e 's/TGL04/PROJECT_LIEUTENANT/g' data/*.txt
perl -p -i -e 's/IMPLY/LIEUTENANT/g' data/*.txt
perl -p -i -e 's/TGL05/PROJECT_CHAMELEON/g' data/*.txt
perl -p -i -e 's/CFI400945/CHAMELEON/g' data/*.txt
perl -p -i -e 's/TGL06/PROJECT_PEBBLE/g' data/*.txt
perl -p -i -e 's/GLORY/PEBBLE/g' data/*.txt
perl -p -i -e 's/TGL07/PROJECT_SWISH/g' data/*.txt
perl -p -i -e 's/REACT/SWISH/g' data/*.txt
perl -p -i -e 's/TGL08/PROJECT_GAMETE/g' data/*.txt
perl -p -i -e 's/LANS/GAMETE/g' data/*.txt
perl -p -i -e 's/TGL09/PROJECT_ENDORPHINS/g' data/*.txt
perl -p -i -e 's/METADUR/ENDORPHINS/g' data/*.txt
perl -p -i -e 's/TGL10/PROJECT_GNATS/g' data/*.txt
perl -p -i -e 's/GENIUS/GNATS/g' data/*.txt
perl -p -i -e 's/TGL11/PROJECT_PUERH/g' data/*.txt
perl -p -i -e 's/LACEBIO/PUERH/g' data/*.txt
perl -p -i -e 's/TGL12/PROJECT_SURREAL/g' data/*.txt
perl -p -i -e 's/MERCASO/SURREAL/g' data/*.txt
perl -p -i -e 's/TGL13/PROJECT_COCKAREL/g' data/*.txt
perl -p -i -e 's/LYFL/COCKAREL/g' data/*.txt
perl -p -i -e 's/TGL14/PROJECT_KIROI/g' data/*.txt
perl -p -i -e 's/TSP/KIROI/g' data/*.txt
perl -p -i -e 's/TGL15/PROJECT_SIGMA/g' data/*.txt
perl -p -i -e 's/IBD/SIGMA/g' data/*.txt
perl -p -i -e 's/TGL16/PROJECT_JAVABEAN/g' data/*.txt
perl -p -i -e 's/TGL17/PROJECT_DEFME/g' data/*.txt
perl -p -i -e 's/COMPARISON/DEFME/g' data/*.txt
perl -p -i -e 's/TGL20/PROJECT_SEQTHNG/g' data/*.txt
perl -p -i -e 's/AMINO/SEQTHNG/g' data/*.txt
perl -p -i -e 's/TGL22/PROJECT_CANMAN/g' data/*.txt
perl -p -i -e 's/PHL093/CANMAN/g' data/*.txt
perl -p -i -e 's/TGL24/PROJECT_WIZARD/g' data/*.txt
perl -p -i -e 's/PBRAT/WIZARD/g' data/*.txt
perl -p -i -e 's/TGL25/PROJECT_SUPERHELLO/g' data/*.txt
perl -p -i -e 's/SCOUT/SUPERHELLO/g' data/*.txt
perl -p -i -e 's/TGL27/PROJECT_TINFOIL/g' data/*.txt
perl -p -i -e 's/TGL28/PROJECT_EXTREME/g' data/*.txt
perl -p -i -e 's/TGL30/PROJECT_OXFORDCOMMA/g' data/*.txt
perl -p -i -e 's/TGL31/PROJECT_DOTDOTDOT/g' data/*.txt
perl -p -i -e 's/TGL40/PROJECT_LULLABY/g' data/*.txt
perl -p -i -e 's/TGL41/PROJECT_TREBUCHET/g' data/*.txt
perl -p -i -e 's/TGL49/PROJECT_ZED/g' data/*.txt
perl -p -i -e 's/LFS/PROJECT_FARSCAPE/g' data/*.txt
perl -p -i -e 's/OCT/PROJECT_SQUID/g' data/*.txt
perl -p -i -e 's/TGL/XYZ/g' data/*.txt
perl -p -i -e 's/COM/WHZ/g' data/*.txt
perl -p -i -e 's/FARSHAD/HILL/g' data/*.txt
perl -p -i -e 's/IMP/DEV/g' data/*.txt
perl -p -i -e 's/DIAM/RED/g' data/*.txt
perl -p -i -e 's/VAL1/PROJECT_QUARTZ/g' data/*.txt
perl -p -i -e 's/GLCS/PROJECT_COSMICCRISP/g' data/*.txt
